# Covariance Matrix

## Install libraries

In [1]:
import sys
!{sys.executable} -m pip install -r requirements.txt

    100% |████████████████████████████████| 12.2MB 1.6MB/s eta 0:00:01   15% |█████                           | 1.9MB 17.1MB/s eta 0:00:01    20% |██████▋                         | 2.5MB 13.1MB/s eta 0:00:01    30% |█████████▊                      | 3.7MB 26.9MB/s eta 0:00:01    35% |███████████▏                    | 4.3MB 10.7MB/s eta 0:00:01    40% |████████████▉                   | 4.9MB 27.9MB/s eta 0:00:01    55% |█████████████████▉              | 6.8MB 27.9MB/s eta 0:00:01    75% |████████████████████████        | 9.1MB 27.4MB/s eta 0:00:01    79% |█████████████████████████▍      | 9.7MB 21.5MB/s eta 0:00:01    84% |███████████████████████████     | 10.3MB 12.6MB/s eta 0:00:01    97% |███████████████████████████████▏| 11.8MB 12.7MB/s eta 0:00:01
tensorflow 1.3.0 requires tensorflow-tensorboard<0.2.0,>=0.1.0, which is not installed.
  Found existing installation: numpy 1.12.1
    Uninstalling numpy-1.12.1:
      Successfully uninstalled numpy-1.12.1


## Imports

In [2]:
import numpy as np
import quiz_tests

## Hints

### covariance matrix
If we have $m$ stock series, the covariance matrix is an $m \times m$ matrix containing the covariance between each pair of stocks.  We can use [numpy.cov](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html) to get the covariance.  We give it a 2D array in which each row is a stock series, and each column is an observation at the same period of time.

The covariance matrix $\mathbf{P} = 
\begin{bmatrix}
\sigma^2_{1,1} & ... & \sigma^2_{1,m} \\ 
... & ... & ...\\
\sigma_{m,1} & ... & \sigma^2_{m,m}  \\
\end{bmatrix}$

## Quiz

In [4]:
import numpy as np

def covariance_matrix(returns):
    """
    Create a function that takes the return series of a set of stocks
    and calculates the covariance matrix.
    
    Parameters
    ----------
    returns : numpy.ndarray
        2D array containing stock return series in each row.
                
    Returns
    -------
    x : np.ndarray
        A numpy ndarray containing the covariance matrix
    """
    
    #covariance matrix of returns
    cov = np.cov(returns)
        
    return cov

quiz_tests.test_covariance_matrix(covariance_matrix)

Tests Passed


In [5]:
"""Test with a 3 simulated stock return series"""
days_per_year = 252
years = 3
total_days = days_per_year * years

return_market = np.random.normal(loc=0.05, scale=0.3, size=days_per_year)
return_1 = np.random.uniform(low=-0.000001, high=.000001, size=days_per_year) + return_market
return_2 = np.random.uniform(low=-0.000001, high=.000001, size=days_per_year) + return_market
return_3 = np.random.uniform(low=-0.000001, high=.000001, size=days_per_year) + return_market
returns = np.array([return_1, return_2, return_3])

"""try out your function"""
cov = covariance_matrix(returns)

print(f"The covariance matrix is \n{cov}")

The covariance matrix is 
[[0.08138925 0.08138926 0.08138925]
 [0.08138926 0.08138926 0.08138926]
 [0.08138925 0.08138926 0.08138925]]


In [7]:
return_1

array([ 0.28778225,  0.41811723, -0.22848425,  0.07470945,  0.2183044 ,
       -0.34456063,  0.27432509, -0.3247947 ,  0.24073305,  0.36844922,
       -0.27682295, -0.04936703,  0.70580093,  0.1480238 , -0.02951248,
        0.14607241,  0.27934691,  0.27136947,  0.02258972, -0.27475431,
        0.14576216,  0.01024956, -0.22125441,  0.20933964,  0.12059867,
        0.02319289, -0.13432949,  0.14203048,  0.01853986,  0.10060111,
        0.32557776,  0.06400576, -0.22504878, -0.06769395,  0.0162533 ,
        0.21928094,  0.09760134, -0.15913914,  0.4147278 ,  0.42593995,
       -0.0466692 , -0.1238378 ,  0.12579318, -0.18149194, -0.04163931,
        0.09181595,  0.26015698, -0.05456864,  0.3423297 , -0.29599191,
        0.22166788, -0.21869775, -0.20588916, -0.11337376,  0.16891969,
       -0.63092956, -0.12627907, -0.19066613, -0.40181673, -0.52982972,
        0.28904301, -0.0303863 , -0.61342372,  0.12363694, -0.34212943,
        0.37196259,  0.02937795,  0.34446174,  0.3089067 ,  0.14

If you're stuck, you can also check out the solution [here](m3l4_covariance_solution.ipynb)